#!/usr/bin/env bash

set -eo pipefail

PROGNAME=$(basename $0)
VERSION="0.0.1"

show_usage() {
  cat <<_EOS_ 1>&2
Usage: $PROGNAME [OPTIONS...]
OPTIONS:
  -h, --help      Show help for '$PROGNAME'
  --profile       string   Use a specific profile from your credential file.
  --region        string   The region to use. Overrides config/env settings.
Examples: 
  $PROGNAME my-dynamodb --profile development --region ap-northeast-1
_EOS_
}

prompt_help () {
  printf "See '$PROGNAME --help' for usage.\n"
}

_get_aws_opt_profile() {
  if [ -v OPT_PROFILE ]; then 
    printf -- "--profile ${OPT_PROFILE}"
  fi
}

_get_aws_opt_region() {
  if [ -v OPT_REGION ]; then 
    printf -- "--region ${OPT_REGION}"
  fi
}

_get_aws_region() {
  printf -- "${OPT_REGION-${AWS_DEFAULT_REGION-$(aws configure get region)}}"
}

dynamo() {
  table=`AWS_PAGER='' aws dynamodb list-tables --query 'TableNames[*][@]' --output text $(_get_aws_opt_region) $(_get_aws_opt_profile) \
    | fzf --ansi --exit-0 --query "$OPT_QUERY"`
    open "https://ap-northeast-1.console.aws.amazon.com/dynamodb/home?region=$(_get_aws_region)#tables:selected=${table};tab=overview"
}

while (( $# > 0 )); do
  case "$1" in
    -h | --help)
      show_usage
      exit 0
      ;;
    --version)
      echo $VERSION
      exit 0
      ;;
    --profile* )
      if [[ "$1" =~ = ]]; then OPT_PROFILE="${1#*=}"; else OPT_PROFILE="$2" && shift; fi
      ;;
    --region* )
      if [[ "$1" =~ = ]]; then OPT_REGION="${1#*=}"; else OPT_REGION="$2" && shift; fi
      ;;
    -* | --* )
      printf "Error: unknown flag: $1\n" 1>&2
      prompt_help
      exit 1
      ;;
    * )
      OPT_QUERY="$1"
      ;;
  esac
  shift
done

dynamo
